version: "3"
services:
  notebook:
    build: .
    container_name: 'python3'
    ports:
      - 8000:8000
    volumes:
      - ./:/workspace
    # 複数実行したいときはbash -c で囲う
    command: bash -c "cd ./workspace && jupyter lab --port 8000 --ip=0.0.0.0 --allow-root"