patch:
 data_dir: /home/higuchi/ssd/kits19/data
 train_patch: tumor_48x48x16
 val_patch: 'tumor_48x48x16'
 train_ids: ['001']
 val_ids: ['002']
# import hparam
exp:
 save_dir: ./tb_logger2
 name: tutorial2
model:
 lr: 0.001
 batch_size: 16
 gpus: 2
 epoch: 5
#  input_shape: [1,16,48,48]
#  label_shape: [3,16,16,16]
trainer:
 gpus: 2
 row_log_interval: 10
 epoch: 5
